<script setup>
  import { ref, onMounted } from 'vue';

  // ⚠️ 这里填你 Worker 后端的地址 (你的主域名)
  // 这样前端就知道去哪里获取验证码和图片了
  const API_BASE = 'https://band.kessoku.us.kg';

  const challenge = ref(null);
  const selectedIndexes = ref([]);
  const message = ref('');
  const isSuccess = ref(false);
  const loading = ref(false);

  // 获取验证码
  const fetchCaptcha = async () => {
    loading.value = true;
      message.value = '';
        isSuccess.value = false;
          selectedIndexes.value = [];
            
              try {
                  const res = await fetch(`${API_BASE}/api/captcha`);
                      if (!res.ok) throw new Error('连接后端失败');
                          const data = await res.json();
                              challenge.value = data;
                                  
                                      // 修复图片路径：后端返回的是 /api/img/xxx，我们需要补全域名
                                          if (challenge.value && challenge.value.images) {
                                                challenge.value.images = challenge.value.images.map(img => {
                                                        return img.startsWith('http') ? img : `${API_BASE}${img}`;
                                                              });
                                                                  }
                                                                    } catch (error) {
                                                                        console.error(error);
                                                                            message.value = '加载失败，请检查网络';
                                                                              } finally {
                                                                                  loading.value = false;
                                                                                    }
                                                                                    };

                                                                                    // 选中/取消选中
                                                                                    const toggleSelect = (index) => {
                                                                                      if (isSuccess.value) return;
                                                                                        if (selectedIndexes.value.includes(index)) {
                                                                                            selectedIndexes.value = selectedIndexes.value.filter(i => i !== index);
                                                                                              } else {
                                                                                                  selectedIndexes.value.push(index);
                                                                                                    }
                                                                                                    };

                                                                                                    // 提交验证
                                                                                                    const verifyCaptcha = async () => {
                                                                                                      if (!challenge.value) return;
                                                                                                        loading.value = true;
                                                                                                          
                                                                                                            try {
                                                                                                                // 1. 发送给后端验证
                                                                                                                    const res = await fetch(`${API_BASE}/api/verify`, {
                                                                                                                            method: 'POST',
                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                            body: JSON.stringify({
                                                                                                                                                        id: challenge.value.id,
                                                                                                                                                                    selectedIndexes: selectedIndexes.value
                                                                                                                                                                            })
                                                                                                                                                                                });
                                                                                                                                                                                    const data = await res.json();

                                                                                                                                                                                        if (data.success) {
                                                                                                                                                                                                isSuccess.value = true;
                                                                                                                                                                                                        message.value = "验证通过！阿里嘎多~";
                                                                                                                                                                                                                
                                                                                                                                                                                                                        // 2. 验证成功，通知父窗口（注册页）
                                                                                                                                                                                                                                setTimeout(() => {
                                                                                                                                                                                                                                            window.parent.postMessage({
                                                                                                                                                                                                                                                            type: 'CAPTCHA_RESULT',
                                                                                                                                                                                                                                                                            payload: {
                                                                                                                                                                                                                                                                                                captchaId: challenge.value.id,
                                                                                                                                                                                                                                                                                                                    selectedIndexes: selectedIndexes.value
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                }, '*');
                                                                                                                                                                                                                                                                                                                                                        }, 800);
                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                    message.value = "选错了哦，再试一次";
                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => { if(!isSuccess.value) fetchCaptcha(); }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                        message.value = "请求出错";
                                                                                                                                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                                                                                                                                loading.value = false;
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                  onMounted(() => {
                                                                                                                                                                                                                                                                                                                                                                                                    fetchCaptcha();
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                    </script>

                                                                                                                                                                                                                                                                                                                                                                                                    <template>
                                                                                                                                                                                                                                                                                                                                                                                                      <div class="captcha-box">
                                                                                                                                                                                                                                                                                                                                                                                                          <div v-if="loading && !challenge" class="loading">加载中...</div>
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                  <div v-else-if="challenge" class="content">
                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="header">
                                                                                                                                                                                                                                                                                                                                                                                                                                请点击所有的 <span class="highlight">{{ challenge.targetName }}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    v-for="(img, index) in challenge.images" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              :key="index"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class="img-item"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  :class="{ active: selectedIndexes.includes(index) }"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @click="toggleSelect(index)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img :src="img" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="check" v-if="selectedIndexes.includes(index)">✓</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button class="btn" @click="fetchCaptcha">刷新</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="btn primary" @click="verifyCaptcha" :disabled="selectedIndexes.length === 0">确认</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div v-if="message" class="msg" :class="{ success: isSuccess }">{{ message }}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div v-else class="error" @click="fetchCaptcha">加载失败，点击重试</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </template>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /* 简单美观的样式 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body { margin: 0; background: transparent; font-family: sans-serif; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .captcha-box { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: white; padding: 15px; border-radius: 12px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 320px; margin: 0 auto; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* 阴影稍微淡一点，因为在遮罩层里 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          box-shadow: 0 4px 12px rgba(0,0,0,0.08); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .header { font-size: 15px; margin-bottom: 10px; color: #333; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .highlight { color: #e91e63; font-weight: bold; font-size: 16px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; margin-bottom: 15px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .img-item { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            aspect-ratio: 1; position: relative; cursor: pointer; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border-radius: 6px; overflow: hidden; border: 2px solid transparent; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .img-item img { width: 100%; height: 100%; object-fit: cover; display: block; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .img-item.active { border-color: #e91e63; transform: scale(0.95); transition: 0.2s; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .check { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                position: absolute; top: 4px; right: 4px; background: #e91e63; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: white; width: 18px; height: 18px; border-radius: 50%; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-align: center; line-height: 18px; font-size: 12px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .footer { display: flex; gap: 10px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .btn { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1; padding: 8px 0; border: none; border-radius: 6px; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: pointer; background: #f5f5f5; font-weight: bold; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .btn.primary { background: #e91e63; color: white; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .msg { margin-top: 10px; text-align: center; font-size: 13px; color: #ff4d4f; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .msg.success { color: #52c41a; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .loading, .error { text-align: center; padding: 30px; color: #999; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>